/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'apple' at '16-10-8 下午8:28' with Gradle 2.14
 *
 * @author apple, @date 16-10-8 下午8:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
